name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  actions: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - run: pnpm exec nx-cloud record -- nx format:check
      - run: pnpm exec nx affected -t lint test build

      - name: Archive AppMaps
        uses: getappmap/archive-action@v1
        with:
          revision: ${{ github.event.pull_request.base.sha }}

      - name: Save AppMaps
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ./tmp/appmap
          key: appmaps-${{ github.sha }}-${{ github.run_attempt }}
  appmap-analysis:
    runs-on: ubuntu-latest
    if: always()
    needs: [main]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - uses:
          getappmap/analyze-action@v1

          # permissions:
          #   actions: read
          #   contents: read
          #   checks: write
          #   pull-requests: write
